### ISSUE TITLE
how configure laravel with Modx?

### ISSUE THREAD

**Issue by marksumoto** [mylgeorge/laravel-modx#1]
Hi, i want integrate Modx with Laravel 5.7 I find this git. can you help me?

**Comment by mylgeorge** [comment]
- Install Laravel
- Install package via composer
`composer require mylgeorge/laravel-modx`
- (optional) export the config file
`php artisan vendor:publish --provider="Modx\Providers\ModxServiceProvider"`
- set MODX_PATH in your .env file pointing to your modx installation folder

Now you have $modx in your views so you can run `$modx->getChunk()` for example
You can also inject modx in you controlers via ModxCMS provider
ex.
```
<?php
use App\Http\Controllers\Controller;
class ModxController extends Controller {
   public function getIndex(ModxCMS $modx){
      return $modx->getChunk('example');
   }
}
```
